# services:
#   mini_serv:
#     image: my_docker:part5
#     build: ../part5
#     container_name: mini_server

#   nginxer:
#     image: nginx:latest
#     container_name: nginxer
#     ports:
#       - 80:8080
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf

services:
  server:
    build: ../part_5
  proxy:
    build: .
    ports:
      - 80:8080
